services:
    postgres:
        image: postgres
        container_name: postgres_db
        ports: 
            - 5432:5432
        env_file: 
            - ./.env
        volumes: 
            - /path-to-volumes/