services:
    postgres:
        image: postgres:13.3-alpine
        environment: 
            POSTGRES_DB: test
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
        ports: 
            - 5432:5432
        volumes: 
            - postgres_data:<path-to-volumes>

volumes: 
    postgres_data: 